# 
# more information can be found here http://sonata-project.org/bundles/user
#
fos_user:
    db_driver:      orm # can be orm or odm
    firewall_name:  main
    user_class:     Ailove\UserBundle\Entity\User
    use_username_form_type: true
    from_email:
        address:        %mailer_from_email%
        sender_name:    %mailer_from_name%
    registration:
        form:
            handler: ailove.form.handler.registration

    group:
        group_class: Application\Sonata\UserBundle\Entity\Group

# Enable Doctrine to map the provided entities
doctrine:
    orm:
        entity_managers:
            default:
                mappings:
                    FOSUserBundle: ~
                    AiloveUserBundle: ~
                    SonataUserBundle: ~
                    ApplicationSonataUserBundle: ~
