sonata_notification:
    backend: sonata.notification.backend.runtime
#    backend: sonata.notification.backend.doctrine
#    backend: sonata.notification.backend.rabbitmq

    backends:
        rabbitmq:
            exchange: router
            queue:    msgs
            connection:
                host:     localhost
                user:     guest
                pass:     guest
                port:     5672
                vhost:    /

doctrine:
    orm:
        entity_managers:
            default:
                mappings:
                    SonataNotificationBundle: ~